################################################################################
#
# qt6qt5compat
#
################################################################################

QT6QT5COMPAT_VERSION = $(QT6_VERSION)
QT6QT5COMPAT_SITE = $(QT6_SITE)
QT6QT5COMPAT_SOURCE = qt5compat-$(QT6_SOURCE_TARBALL_PREFIX)-$(QT6QT5COMPAT_VERSION).tar.xz
QT6QT5COMPAT_INSTALL_STAGING = YES
QT6QT5COMPAT_LICENSE = GPL-2.0+ or LGPL-3.0, GPL-3.0 with exception(tools)
QT6QT5COMPAT_LICENSE_FILES = LICENSE.GPL2 LICENSE.GPL3 LICENSE.GPL3-EXCEPT LICENSE.LGPL3

QT6QT5COMPAT_DEPENDENCIES = \
	host-ninja \
	qt6base

QT6QT5COMPAT_CONF_OPTS += \
	-GNinja \
	-DQT_HOST_PATH=$(HOST_DIR) \

QT6QT5COMPAT_MAKE = ninja
QT6QT5COMPAT_INSTALL_STAGING_OPTS = install
QT6QT5COMPAT_INSTALL_STAGING_ENV = DESTDIR="$(STAGING_DIR)"
QT6QT5COMPAT_INSTALL_TARGET_OPTS = install
QT6QT5COMPAT_INSTALL_TARGET_ENV = DESTDIR="$(TARGET_DIR)"

$(eval $(cmake-package))
