################################################################################
#
# qt6virtualkeybord
#
################################################################################

QT6VIRTUALKEYBOARD_VERSION = $(QT6_VERSION)
QT6VIRTUALKEYBOARD_SITE = $(QT6_SITE)
QT6VIRTUALKEYBOARD_SOURCE = qtvirtualkeyboard-$(QT6_SOURCE_TARBALL_PREFIX)-$(QT6VIRTUALKEYBOARD_VERSION).tar.xz
QT6VIRTUALKEYBOARD_INSTALL_STAGING = YES
QT6VIRTUALKEYBOARD_LICENSE = GPL-3.0
QT6VIRTUALKEYBOARD_LICENSE_FILES = LICENSE.GPL3

QT6VIRTUALKEYBOARD_DEPENDENCIES = \
	host-ninja \
	qt6base \
	qt6declarative \
	qt6svg

QT6VIRTUALKEYBOARD_MAKE = ninja
QT6VIRTUALKEYBOARD_INSTALL_STAGING_OPTS = install
QT6VIRTUALKEYBOARD_INSTALL_STAGING_ENV = DESTDIR="$(STAGING_DIR)"
QT6VIRTUALKEYBOARD_INSTALL_TARGET_OPTS = install
QT6VIRTUALKEYBOARD_INSTALL_TARGET_ENV = DESTDIR="$(TARGET_DIR)"

QT6VIRTUALKEYBOARD_CONF_OPTS += \
	-GNinja \
	-DQT_HOST_PATH=$(HOST_DIR) \

ifeq ($(BR2_PACKAGE_QT6VIRTUALKEYBOARD_ARROW_KEY_NAVIGATION),y)
QT6VIRTUALKEYBOARD_CONF_OPTS += -DQT_FEATURE_vkb_arrow_keynavigation=ON
endif

$(eval $(cmake-package))
