################################################################################
#
# qt6shadertools
#
################################################################################

QT6SHADERTOOLS_VERSION = $(QT6_VERSION)
QT6SHADERTOOLS_SITE = $(QT6_SITE)
QT6SHADERTOOLS_SOURCE = qtshadertools-$(QT6_SOURCE_TARBALL_PREFIX)-$(QT6SHADERTOOLS_VERSION).tar.xz
QT6SHADERTOOLS_INSTALL_STAGING = YES
QT6SHADERTOOLS_LICENSE = GPL-2.0+ or LGPL-3.0, GPL-3.0 with exception(tools)
QT6SHADERTOOLS_LICENSE_FILES = LICENSE.GPL2 LICENSE.GPL3 LICENSE.GPL3-EXCEPT LICENSE.LGPL3

QT6SHADERTOOLS_DEPENDENCIES = \
	host-ninja \
	host-qt6shadertools

QT6SHADERTOOLS_CONF_OPTS += \
	-GNinja \
	-DQT_HOST_PATH=$(HOST_DIR)

QT6SHADERTOOLS_MAKE = ninja
QT6SHADERTOOLS_INSTALL_STAGING_OPTS = install
QT6SHADERTOOLS_INSTALL_STAGING_ENV = DESTDIR="$(STAGING_DIR)"
QT6SHADERTOOLS_INSTALL_TARGET_OPTS = install
QT6SHADERTOOLS_INSTALL_TARGET_ENV = DESTDIR="$(TARGET_DIR)"

HOST_QT6SHADERTOOLS_DEPENDENCIES = host-ninja host-zlib
HOST_QT6SHADERTOOLS_MAKE = ninja
HOST_QT6SHADERTOOLS_CONF_OPTS += \
	-GNinja \
	-DCMAKE_DESTDIR=$(HOST_DIR) \
	-DCMAKE_INSTALL_PREFIX=$(HOST_DIR) \
	-DCMAKE_INSTALL_RPATH=$(HOST_DIR)/lib \
	-DBUILD_SHARED_LIBS=OFF \


$(eval $(cmake-package))
$(eval $(host-cmake-package))
